#ifndef __EvtFramePrincipal__
#define __EvtFramePrincipal__

/**
@file
Subclass of FramePrincipal, which is generated by wxFormBuilder.
*/

#include "FramePrincipal.h"

//// end generated include
enum
{
ID_THREAD_ACQUISITIONCB= 201,
ID_THREAD_GESTIONCB,
ID_THREAD_IMPRESSION
};

class ThreadAcquisitionCB;
class ThreadGestionCB;
class ThreadImpression;
#include "CommunicationThread.h"
using namespace std;

/** Implementing FramePrincipal */
class EvtFramePrincipal : public FramePrincipal
{
	protected:
		// Handlers for FramePrincipal events.
		void OnClose_Click( wxCloseEvent& event );
		void OnButton_passage_non_scolaire_Click( wxCommandEvent& event );
		void OnButton_passage_scolaire_Click( wxCommandEvent& event );
		void OnButton_passage_inconnu_Click( wxCommandEvent& event );
		void OnButton_pass_Click( wxCommandEvent& event );
	public:
		/** Constructor */
		EvtFramePrincipal( wxWindow* parent );
	//// end generated class members
private:
    CommunicationThread *m_communication_pcb;
    CommunicationThread *m_communication_impression;
    bool m_Thread_AcquisitioncbFini, m_Thread_Gestioncbfini, m_Thread_Impressionfini;
    ThreadAcquisitionCB *m_thread_Acquisition;
    ThreadGestionCB *m_thread_Gestion;
    ThreadImpression *m_thread_Impression;

    void OnThread_Acquisition_Event(wxCommandEvent& event);
    void OnThread_Gestion_Event(wxCommandEvent& event);





};

#endif // __EvtFramePrincipal__
