.PHONY: clean All

All:
	@echo "----------Building project:[ restauration - Debug ]----------"
	@cd "restauration" && "$(MAKE)" -f  "restauration.mk"
clean:
	@echo "----------Cleaning project:[ restauration - Debug ]----------"
	@cd "restauration" && "$(MAKE)" -f  "restauration.mk" clean
